apiVersion: v1
kind: Service
metadata:
  name: {{ include "aicacia-user.fullname" . }}
  labels: {{ - include "aicacia-user.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ - include "aicacia-user.selectorLabels" . | nindent 4 }}
