apiVersion: v2
name: aicacia-id
description: aicacia peer to peer rooms
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: postgresql
    version: 10.3.17
    repository: https://charts.bitnami.com/bitnami