replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 90

image:
  repository: registry.aicacia.com/api/aicacia_id
  tag: 0.1.0
  pullPolicy: Always
  hash: sha256:13ba025b6c186da3fdce3db68f192721fef8300ae02f2ae76c953d771b7180e4

env:
  MIX_ENV: prod

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/secure-backends: "true"
  hosts:
    - host: api.user.aicacia.com
      paths:
        - /
  tls:
    - secretName: api-user-aicacia-com-tls
      hosts:
        - api.user.aicacia.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

configMaps: {}
